// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSaftHN0TwITMPx8jKyvVFB0sKTLuqCSM',
    appId: '1:1002703289584:web:42df647c4b55ea31459635',
    messagingSenderId: '1002703289584',
    projectId: 'e-commerce-uet-project',
    authDomain: 'e-commerce-uet-project.firebaseapp.com',
    storageBucket: 'e-commerce-uet-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPEMcnMLqPiEjbYzdQ64CjG41nIqezNOk',
    appId: '1:1002703289584:android:52775c5787953e3f459635',
    messagingSenderId: '1002703289584',
    projectId: 'e-commerce-uet-project',
    storageBucket: 'e-commerce-uet-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg1YvYRlk8iJBr5zqnZ9CaN8WkpMI7i9w',
    appId: '1:1002703289584:ios:8318acc1950afb9d459635',
    messagingSenderId: '1002703289584',
    projectId: 'e-commerce-uet-project',
    storageBucket: 'e-commerce-uet-project.appspot.com',
    iosClientId: '1002703289584-or9ncnt9appnbdnbln95grg8ar5h0a2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg1YvYRlk8iJBr5zqnZ9CaN8WkpMI7i9w',
    appId: '1:1002703289584:ios:46ff397ca285648b459635',
    messagingSenderId: '1002703289584',
    projectId: 'e-commerce-uet-project',
    storageBucket: 'e-commerce-uet-project.appspot.com',
    iosClientId: '1002703289584-oacnnecpn2e2ql56c0agi225b7qlbc0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAppMobile.RunnerTests',
  );
}
